import AdminSidebar from "@/components/AdminSidebar";
import Header from "@/components/Header";
import Wrapper from "@/components/Wrapper";
import "@/styles/index.scss";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
});

const conthrax = localFont({
    src: "../../../public/fonts/conthrax-sb.ttf",
    variable: "--font-conthrax",
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${montserrat.variable} ${conthrax.variable}  antialiased`}>
                <Header />
                <Wrapper>
                    <div className="flex h-screen">
                        <AdminSidebar />
                        <main className="flex-1 overflow-auto p-4">{children}</main>
                    </div>

                </Wrapper>
            </body>
        </html>
    );
}
