import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "@/styles/index.scss";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "../globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const conthrax = localFont({
  src: "../../../public/fonts/conthrax-sb.ttf",
  variable: "--font-conthrax",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${conthrax.variable}  antialiased`}>
        <Toaster />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
